FROM 172.16.20.150:5000/zelixir:enterprise

#copy mmpbsa conda env
COPY /share/zhengliangzhen/apps/DNAWorks /private/zdaemon/enterprise/apps/DNAworks/DNAworks-release-latest

#copy mmpbsa release apps
COPY /share/zhengliangzhen/apps/pacDock-TBM/envs/pacdocktbm /private/zdaemon/enterprise/conda/DNAworks

